CREATE TABLE WEATHER(
WEATHER_CODE INT NOT NULL PRIMARY KEY,
DESCRIPTION VARCHAR(100) NOT NULL
);

CREATE TABLE CITY(
CITY_ID BIGINT NOT NULL PRIMARY KEY,
CITY_NAME VARCHAR(50),
STATE_CODE INT,
COUNTRY_CODE VARCHAR(2),
COUNTRY_NAME VARCHAR(50),
LATITUDE DECIMAL(9,6) NOT NULL,
LONGITUDE DECIMAL(9,6) NOT NULL,
OBSERVATION_DATE DATE NOT NULL,
WEATHER_CODE INT NOT NULL
);


ALTER TABLE CITY ADD FOREIGN KEY (WEATHER_CODE) REFERENCES WEATHER(WEATHER_CODE);
